name: goreleaser

on:
  push:
    tags:
      - '*'

  # Allows manual triggering of the workflow
  workflow_dispatch:

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v5

      -
        name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'  # or your preferred version
      -
        name: Install dependencies and build UI
        run: |
          cd ui
          npm ci
          npm run build

      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}